### PR TITLE
Implement JS unit test framework and CI pipeline actions

### LINKED ISSUE #33: Implement JS Unit Test Framework
Implement or use an existing framework for JavaScript unit testing. The framework should fulfil the following requirements:
- Uses assertions to check inputs against expected outputs
- Assertions should perform both loose and strict checking (== and ===) and respond accordingly
- Assertions should work on complex outputs such as objects and lists
- Tests should be a collection of assertions defined through code 
- Tests should identify errors and correctly print errors as needed
- Tests may identify warnings such as incorrect typing and print messages as needed
- Tests should exit with the correct system exit codes to correctly integrate with GitHub actions

Tests should be written for the unit test framework:
- Test if assertions work with simple types
- Test if assertions work with objects
- Test if tests have correct exit codes

### LINKED ISSUE #34: Implement JS Unit Test CI Pipeline
Implement a GitHub actions workflow that uses the JS Unit Test framework to automatically test repository code. The pipeline should have the following details:
- Triggered on specific events TBD
- Runs the unit tests and outputs any errors or failed tests encountered
- Correctly outputs a passed or failed state depending on unit test results
- Correctly blocks or allows PR merging depending on state

### PR DESCRIPTION
**Pull request by ltcptgeneral**
- Use mocha for JS unit testing framework
- Created testenv package for emulating localStorage behavior
- Add unit tests to testenv
- Add js-unittest.yml to workflows to automate unit testing on each PR to main

### CODE REVIEW

**Review by KH-Cl — APPROVED** [review]
Looks good

**Review by Graydogminer — APPROVED** [review]
Looks good!

**Review by d7hernan — APPROVED** [review]
looks good!

**Review by KH-Cl — CHANGES_REQUESTED** [review]
changes pls

**Review by KH-Cl — APPROVED** [review]
:)

**Pull request merged**
